//! Device identity and recovery policy for providers that report device sets to Bevy.

mod attempt;
mod binding;
mod capabilities;
mod claim;
mod contract;
mod discovery;
mod endpoint;
mod evidence;
mod fault;
mod identity;
mod plugin;
mod policy;
mod presence;
mod recovery;
mod registration;
mod role;
mod scheme;
mod verdict;

pub use attempt::AttemptId;
pub use attempt::AttemptOutcome;
pub use attempt::AttemptProgress;
pub use attempt::LastKnownGoodConfiguration;
pub use binding::ApplyingRole;
pub use binding::AvailableConfiguration;
pub use binding::Binding;
pub use binding::BindingCapacityError;
pub use binding::BindingError;
pub use binding::BindingTransition;
pub use binding::BindingTransitionSequence;
pub use binding::Bindings;
pub use binding::CaptureRequest;
pub use binding::ConfiguredDevice;
pub use binding::ConfiguredDeviceConnection;
pub use binding::ConfiguredDeviceMode;
pub use binding::HardwareInventory;
pub use binding::HardwareInventoryError;
pub use binding::PollRequest;
pub use binding::ReadyRole;
pub use binding::RequestedConfiguration;
pub use binding::RetirementOutcome;
pub use binding::RoleView;
pub use binding::StartApplyRequest;
pub use binding::WaitingRole;
pub use capabilities::Capabilities;
pub use capabilities::CapabilityAttachError;
pub use claim::Claim;
pub use claim::ClaimHolder;
pub use claim::PermissionGate;
pub use contract::CaptureOutcome;
pub use contract::DeviceReporter;
pub use contract::DiscoveryJob;
pub use contract::DiscoveryProgress;
pub use contract::DiscoveryProgressSendError;
pub use contract::DiscoveryProgressSender;
pub use contract::DiscoveryWork;
pub use contract::DriverContractError;
pub use contract::EndpointDriver;
pub use contract::MainThreadDiscoveryJob;
pub use discovery::AuthoritativeReporterCoverage;
pub use discovery::AuthoritativeReporterCoverageError;
pub use discovery::CoveredDeviceIdentitySpace;
pub use discovery::DiscoveryBatchId;
pub use discovery::DiscoveryCadence;
pub use discovery::DiscoveryControl;
pub use discovery::DiscoveryControlError;
pub use discovery::DiscoveryLimits;
pub use discovery::DiscoverySchedulerError;
pub use discovery::DiscoverySchedulerState;
pub use discovery::DiscoveryStatus;
pub use discovery::DiscoveryStatusError;
pub use discovery::LastDiscoveryOutcome;
pub use discovery::ReporterActivation;
pub use discovery::ReporterActivity;
pub use discovery::ReporterCoverage;
pub use discovery::ReporterDiscoveryStatus;
pub use discovery::ReporterRegistration;
pub use discovery::StartupDiscoveryState;
pub use discovery::hardware_ready;
pub use endpoint::DeviceEndpoint;
pub use endpoint::EndpointId;
pub use endpoint::PartName;
pub use endpoint::PartNameError;
pub use evidence::AttachmentPath;
pub use evidence::DeviceDescriptor;
pub use evidence::OsDeviceId;
pub use fault::DeviceAccessError;
pub use identity::DeviceId;
pub use identity::DeviceIdSource;
pub use identity::DeviceKey;
pub use identity::DeviceKind;
pub use plugin::RiggingPlugin;
pub use plugin::RiggingSystems;
pub use policy::OnAbort;
pub use policy::OnSessionLoss;
pub use policy::RetryOn;
pub use presence::DeviceRecord;
pub use presence::DeviceScan;
pub use presence::DeviceSet;
pub use presence::Presence;
pub use presence::ReportedAs;
pub use presence::ReporterId;
pub use presence::ReporterRevision;
pub use recovery::RecoveryPolicy;
pub use registration::ApplyPermit;
pub use registration::DriverId;
pub use registration::RiggingAppExt;
pub use role::RoleKey;
pub use role::RoleKeyError;
pub use role::RoleState;
pub use scheme::AuthoredId;
pub use scheme::AuthoredIdError;
pub use scheme::Digest;
pub use scheme::RegisteredSchemes;
pub use scheme::ReportedId;
pub use scheme::ReportedIdError;
pub use scheme::SchemeName;
pub use scheme::SchemeNameError;
pub use scheme::UnregisteredSchemeError;
pub use verdict::IdentityVerdict;
pub use verdict::ReportedSerial;
pub use verdict::UnverifiedReason;

/// Common types for reporting devices to the kernel and for reading the identity verdicts it
/// returns.
pub mod prelude {
    pub use crate::ApplyPermit;
    pub use crate::ApplyingRole;
    pub use crate::AttachmentPath;
    pub use crate::AttemptId;
    pub use crate::AttemptOutcome;
    pub use crate::AttemptProgress;
    pub use crate::AuthoredId;
    pub use crate::AuthoredIdError;
    pub use crate::AuthoritativeReporterCoverage;
    pub use crate::AuthoritativeReporterCoverageError;
    pub use crate::AvailableConfiguration;
    pub use crate::Binding;
    pub use crate::BindingCapacityError;
    pub use crate::BindingError;
    pub use crate::BindingTransition;
    pub use crate::BindingTransitionSequence;
    pub use crate::Bindings;
    pub use crate::Capabilities;
    pub use crate::CapabilityAttachError;
    pub use crate::CaptureOutcome;
    pub use crate::CaptureRequest;
    pub use crate::Claim;
    pub use crate::ClaimHolder;
    pub use crate::ConfiguredDevice;
    pub use crate::ConfiguredDeviceConnection;
    pub use crate::ConfiguredDeviceMode;
    pub use crate::CoveredDeviceIdentitySpace;
    pub use crate::DeviceAccessError;
    pub use crate::DeviceDescriptor;
    pub use crate::DeviceEndpoint;
    pub use crate::DeviceId;
    pub use crate::DeviceIdSource;
    pub use crate::DeviceKey;
    pub use crate::DeviceKind;
    pub use crate::DeviceRecord;
    pub use crate::DeviceReporter;
    pub use crate::DeviceScan;
    pub use crate::DeviceSet;
    pub use crate::Digest;
    pub use crate::DiscoveryBatchId;
    pub use crate::DiscoveryCadence;
    pub use crate::DiscoveryControl;
    pub use crate::DiscoveryControlError;
    pub use crate::DiscoveryJob;
    pub use crate::DiscoveryLimits;
    pub use crate::DiscoveryProgress;
    pub use crate::DiscoveryProgressSendError;
    pub use crate::DiscoveryProgressSender;
    pub use crate::DiscoverySchedulerError;
    pub use crate::DiscoverySchedulerState;
    pub use crate::DiscoveryStatus;
    pub use crate::DiscoveryStatusError;
    pub use crate::DiscoveryWork;
    pub use crate::DriverContractError;
    pub use crate::DriverId;
    pub use crate::EndpointDriver;
    pub use crate::EndpointId;
    pub use crate::HardwareInventory;
    pub use crate::HardwareInventoryError;
    pub use crate::IdentityVerdict;
    pub use crate::LastDiscoveryOutcome;
    pub use crate::LastKnownGoodConfiguration;
    pub use crate::MainThreadDiscoveryJob;
    pub use crate::OnAbort;
    pub use crate::OnSessionLoss;
    pub use crate::OsDeviceId;
    pub use crate::PartName;
    pub use crate::PartNameError;
    pub use crate::PermissionGate;
    pub use crate::PollRequest;
    pub use crate::Presence;
    pub use crate::ReadyRole;
    pub use crate::RecoveryPolicy;
    pub use crate::RegisteredSchemes;
    pub use crate::ReportedAs;
    pub use crate::ReportedId;
    pub use crate::ReportedIdError;
    pub use crate::ReportedSerial;
    pub use crate::ReporterActivation;
    pub use crate::ReporterActivity;
    pub use crate::ReporterCoverage;
    pub use crate::ReporterDiscoveryStatus;
    pub use crate::ReporterId;
    pub use crate::ReporterRegistration;
    pub use crate::ReporterRevision;
    pub use crate::RequestedConfiguration;
    pub use crate::RetirementOutcome;
    pub use crate::RetryOn;
    pub use crate::RiggingAppExt;
    pub use crate::RiggingPlugin;
    pub use crate::RiggingSystems;
    pub use crate::RoleKey;
    pub use crate::RoleKeyError;
    pub use crate::RoleState;
    pub use crate::RoleView;
    pub use crate::SchemeName;
    pub use crate::SchemeNameError;
    pub use crate::StartApplyRequest;
    pub use crate::StartupDiscoveryState;
    pub use crate::UnregisteredSchemeError;
    pub use crate::UnverifiedReason;
    pub use crate::WaitingRole;
    pub use crate::hardware_ready;
}
