//! Device identity and recovery policy for providers that report device sets to Bevy.

mod attempt;
mod capabilities;
mod claim;
mod endpoint;
mod evidence;
mod fault;
mod identity;
mod policy;
mod presence;
mod recovery;
mod role;
mod scheme;
mod verdict;

pub use attempt::AttemptId;
pub use attempt::AttemptOutcome;
pub use attempt::AttemptProgress;
pub use attempt::CapturedConfiguration;
pub use capabilities::Capabilities;
pub use capabilities::CapabilityAttachError;
pub use claim::Claim;
pub use claim::ClaimHolder;
pub use claim::PermissionGate;
pub use endpoint::DeviceEndpoint;
pub use endpoint::EndpointId;
pub use endpoint::PartName;
pub use endpoint::PartNameError;
pub use evidence::AttachmentPath;
pub use evidence::DeviceDescriptor;
pub use evidence::OsDeviceId;
pub use fault::DeviceAccessError;
pub use identity::DeviceId;
pub use identity::DeviceIdSource;
pub use identity::DeviceKey;
pub use identity::DeviceKind;
pub use policy::OnAbort;
pub use policy::OnSessionLoss;
pub use policy::RetryOn;
pub use presence::DeviceRecord;
pub use presence::DeviceScan;
pub use presence::DeviceSet;
pub use presence::Presence;
pub use presence::ReportedAs;
pub use presence::ReporterId;
pub use presence::ReporterRevision;
pub use recovery::RecoveryPolicy;
pub use role::RoleKey;
pub use role::RoleKeyError;
pub use role::RoleState;
pub use scheme::Digest;
pub use scheme::RegisteredSchemes;
pub use scheme::ReportedId;
pub use scheme::ReportedIdError;
pub use scheme::SchemeName;
pub use scheme::SchemeNameError;
pub use scheme::UnregisteredSchemeError;
pub use verdict::IdentityVerdict;
pub use verdict::ReportedSerial;
pub use verdict::UnverifiedReason;

/// Common types for reporting devices to the kernel and for reading the identity verdicts it
/// returns.
pub mod prelude {
    pub use crate::AttachmentPath;
    pub use crate::AttemptId;
    pub use crate::AttemptOutcome;
    pub use crate::AttemptProgress;
    pub use crate::Capabilities;
    pub use crate::CapabilityAttachError;
    pub use crate::CapturedConfiguration;
    pub use crate::Claim;
    pub use crate::ClaimHolder;
    pub use crate::DeviceAccessError;
    pub use crate::DeviceDescriptor;
    pub use crate::DeviceEndpoint;
    pub use crate::DeviceId;
    pub use crate::DeviceIdSource;
    pub use crate::DeviceKey;
    pub use crate::DeviceKind;
    pub use crate::DeviceRecord;
    pub use crate::DeviceScan;
    pub use crate::DeviceSet;
    pub use crate::Digest;
    pub use crate::EndpointId;
    pub use crate::IdentityVerdict;
    pub use crate::OnAbort;
    pub use crate::OnSessionLoss;
    pub use crate::OsDeviceId;
    pub use crate::PartName;
    pub use crate::PartNameError;
    pub use crate::PermissionGate;
    pub use crate::Presence;
    pub use crate::RecoveryPolicy;
    pub use crate::RegisteredSchemes;
    pub use crate::ReportedAs;
    pub use crate::ReportedId;
    pub use crate::ReportedIdError;
    pub use crate::ReportedSerial;
    pub use crate::ReporterId;
    pub use crate::ReporterRevision;
    pub use crate::RetryOn;
    pub use crate::RoleKey;
    pub use crate::RoleKeyError;
    pub use crate::RoleState;
    pub use crate::SchemeName;
    pub use crate::SchemeNameError;
    pub use crate::UnregisteredSchemeError;
    pub use crate::UnverifiedReason;
}
