[package]
edition = "2021"
name    = "hana_visualization"
version = "0.1.0"

[dependencies]
bevy.workspace         = true
hana_network.workspace = true
tokio.workspace        = true
tracing.workspace      = true
