include = [
  "**/Cargo.toml",
  ".rustfmt.toml",
  ".taplo.toml",
  "bacon.toml",
  "docs/book.toml",
]

[formatting]
align_entries  = true
reorder_arrays = true
reorder_keys   = true

[[rule]]
include = ["bacon.toml"]

[rule.formatting]
reorder_arrays = false
