[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace]
default-members = [
  "crates/hana",
  "crates/hana_async",
  "crates/hana_const",
  "crates/hana_input",
  "crates/hana_network",
  "crates/hana_plugin",
  "crates/hana_process",
  "crates/hana_viz",
  "examples/basic_visualization",
]
members = [
  "crates/hana",
  "crates/hana_async",
  "crates/hana_const",
  "crates/hana_input",
  "crates/hana_network",
  "crates/hana_plugin",
  "crates/hana_process",
  "crates/hana_viz",
  "examples/basic_visualization",
]
resolver = "2"

[workspace.lints.clippy]
expect_used = "deny"
panic       = "deny"
unwrap_used = "deny"

[workspace.dependencies]
#
# Workspace member crates
#
hana_async = { path = "crates/hana_async" }
hana_const = { path = "crates/hana_const" }
# hana_input   = { path = "crates/hana_input" }
hana_network = { path = "crates/hana_network" }
hana_plugin  = { path = "crates/hana_plugin" }
hana_process = { path = "crates/hana_process" }
hana_viz     = { path = "crates/hana_viz" }

#
# External dependencies
#
bevy        = "^0.15.3"
error-stack = { version = "0.5.0", features = ["spantrace"] }
flume       = "0.11.1"

tempfile = "3.18.0"
thiserror = "2.0.12"
tokio = { version = "1.44", default-features = false, features = [
  "io-util",         # for AsyncReadExt, AsyncWriteExt
  "macros",          # for #[tokio::main]
  "net",             # for TcpStream
  "process",         # for process::Command
  "rt-multi-thread", # for multithreaded runtime
  "sync",            # for mpsc::channel
  "time",            # for sleep
] }
tracing = "0.1.41"

[profile.dev.package]
bevy = { opt-level = 3 }
