use bevy::asset::RenderAssetUsages;
use bevy::camera::visibility::NoFrustumCulling;
use bevy::camera::visibility::RenderLayers;
use bevy::color::LinearRgba;
use bevy::light::NotShadowCaster;
use bevy::mesh::Indices;
use bevy::mesh::MeshVertexBufferLayoutRef;
use bevy::pbr::ExtendedMaterial;
use bevy::pbr::MaterialExtension;
use bevy::pbr::MaterialExtensionKey;
use bevy::pbr::MaterialExtensionPipeline;
use bevy::prelude::*;
use bevy::reflect::TypePath;
use bevy::render::render_resource::AsBindGroup;
use bevy::render::render_resource::CompareFunction;
use bevy::render::render_resource::PrimitiveTopology;
use bevy::render::render_resource::RenderPipelineDescriptor;
use bevy::render::render_resource::SpecializedMeshPipelineError;

use super::frame::FitOverlayLayout;
use super::reconciliation;
use super::screen_space;
use super::visual::FitOverlayVisual;
use super::visual::FitOverlayVisualKind;

pub(super) type FitOverlayLineMaterial = ExtendedMaterial<StandardMaterial, FitOverlayLineDepth>;

/// Material extension that makes overlay lines ignore scene depth.
#[derive(Asset, AsBindGroup, Clone, Debug, Default, TypePath)]
pub(super) struct FitOverlayLineDepth {
    #[uniform(100)]
    _depth_policy: u32,
}

impl MaterialExtension for FitOverlayLineDepth {
    fn alpha_mode() -> Option<AlphaMode> { Some(AlphaMode::Blend) }

    fn enable_prepass() -> bool { false }

    fn enable_shadows() -> bool { false }

    fn specialize(
        _pipeline: &MaterialExtensionPipeline,
        descriptor: &mut RenderPipelineDescriptor,
        _layout: &MeshVertexBufferLayoutRef,
        _key: MaterialExtensionKey<Self>,
    ) -> Result<(), SpecializedMeshPipelineError> {
        if let Some(depth_stencil) = descriptor.depth_stencil.as_mut() {
            depth_stencil.depth_compare = Some(CompareFunction::Always);
            depth_stencil.depth_write_enabled = Some(false);
        }
        Ok(())
    }
}

/// Retained Core3d line visual generated by `FitOverlay`.
#[derive(Component, Reflect, Debug, Clone, Copy, PartialEq)]
#[reflect(Component)]
pub(super) struct FitOverlayLineVisual {
    /// Line color resolved from `FitTargetOverlayConfig`.
    pub(super) color: Color,
    /// Line width in viewport pixels.
    pub(super) width: f32,
}

#[derive(Default, Resource)]
pub(super) struct FitOverlayLineMaterials {
    entries: Vec<FitOverlayLineMaterialEntry>,
}

struct FitOverlayLineMaterialEntry {
    color:  Color,
    handle: Handle<FitOverlayLineMaterial>,
}

impl FitOverlayLineMaterials {
    fn handle(
        &mut self,
        materials: &mut Assets<FitOverlayLineMaterial>,
        color: Color,
    ) -> Handle<FitOverlayLineMaterial> {
        if let Some(entry) = self.entries.iter().find(|entry| entry.color == color) {
            return entry.handle.clone();
        }

        let handle = materials.add(line_material(color));
        self.entries.push(FitOverlayLineMaterialEntry {
            color,
            handle: handle.clone(),
        });
        handle
    }
}

pub(super) type FitOverlayLineQueryItem = (
    Entity,
    &'static FitOverlayVisual,
    Option<&'static RenderLayers>,
    Option<&'static Mesh3d>,
    Option<&'static MeshMaterial3d<FitOverlayLineMaterial>>,
);

#[derive(Clone)]
pub(super) struct RetainedLineEntity {
    entity: Entity,
    visual: FitOverlayVisual,
    layers: Option<RenderLayers>,
    mesh:   Option<Handle<Mesh>>,
}

pub(super) struct FitOverlayLineContext<'a, 'w, 's> {
    pub(super) commands:       &'a mut Commands<'w, 's>,
    pub(super) meshes:         &'a mut Assets<Mesh>,
    pub(super) materials:      &'a mut Assets<FitOverlayLineMaterial>,
    pub(super) material_cache: &'a mut FitOverlayLineMaterials,
    pub(super) line_index:     &'a [RetainedLineEntity],
    pub(super) layout:         &'a FitOverlayLayout,
}

impl FitOverlayLineContext<'_, '_, '_> {
    pub(super) fn upsert_polyline(
        &mut self,
        visual: FitOverlayVisual,
        points: &[Vec2],
        closed: bool,
        color: Color,
        width: f32,
    ) {
        let Some(mesh) = line_mesh(self.layout, points, closed, width) else {
            self.despawn_if_present(visual);
            return;
        };

        let material = self.material_cache.handle(self.materials, color);
        let line_visual = FitOverlayLineVisual { color, width };

        if let Some(line) = retained_line_entity(self.line_index, visual) {
            self.update_existing(line, mesh, material, line_visual);
        } else {
            self.spawn_line(visual, mesh, material, line_visual);
        }
    }

    fn despawn_if_present(&mut self, visual: FitOverlayVisual) {
        if let Some(line) = retained_line_entity(self.line_index, visual) {
            reconciliation::despawn_visual_root(self.commands, line.entity);
        }
    }

    fn update_existing(
        &mut self,
        line: &RetainedLineEntity,
        mesh: Mesh,
        material: Handle<FitOverlayLineMaterial>,
        line_visual: FitOverlayLineVisual,
    ) {
        if let Some(mesh_handle) = &line.mesh {
            if let Some(mut existing_mesh) = self.meshes.get_mut(mesh_handle) {
                *existing_mesh = mesh;
            } else {
                self.commands
                    .entity(line.entity)
                    .insert(Mesh3d(self.meshes.add(mesh)));
            }
        } else {
            self.commands
                .entity(line.entity)
                .insert(Mesh3d(self.meshes.add(mesh)));
        }

        reconciliation::repair_render_layers(
            self.commands,
            line.entity,
            &self.layout.context.layers,
            line.layers.as_ref(),
        );
        self.commands.entity(line.entity).insert((
            MeshMaterial3d(material),
            retained_line_components(self.layout, line_visual),
        ));
    }

    fn spawn_line(
        &mut self,
        visual: FitOverlayVisual,
        mesh: Mesh,
        material: Handle<FitOverlayLineMaterial>,
        line_visual: FitOverlayLineVisual,
    ) {
        self.commands.spawn((
            visual,
            Mesh3d(self.meshes.add(mesh)),
            MeshMaterial3d(material),
            retained_line_components(self.layout, line_visual),
        ));
    }
}

pub(super) fn retained_line_entities(
    line_query: &Query<FitOverlayLineQueryItem, With<FitOverlayLineVisual>>,
) -> Vec<RetainedLineEntity> {
    let mut lines: Vec<RetainedLineEntity> = line_query
        .iter()
        .map(|(entity, visual, layers, mesh, _)| RetainedLineEntity {
            entity,
            visual: *visual,
            layers: layers.cloned(),
            mesh: mesh.map(|mesh| mesh.0.clone()),
        })
        .collect();
    lines.sort_by_key(|line| line.entity);
    lines
}

fn retained_line_entity(
    lines: &[RetainedLineEntity],
    visual: FitOverlayVisual,
) -> Option<&RetainedLineEntity> {
    lines.iter().find(|line| line.visual == visual)
}

pub(super) fn clear_stale_lines(
    commands: &mut Commands,
    camera: Entity,
    desired: &[FitOverlayVisualKind],
    line_query: &Query<(Entity, &FitOverlayVisual), With<FitOverlayLineVisual>>,
) {
    for (entity, visual) in line_query {
        if visual.camera == camera && !desired.contains(&visual.kind) {
            reconciliation::despawn_visual_root(commands, entity);
        }
    }
}

fn retained_line_components(
    layout: &FitOverlayLayout,
    line_visual: FitOverlayLineVisual,
) -> impl Bundle {
    (
        line_visual,
        layout.context.layers.clone(),
        Transform::IDENTITY,
        GlobalTransform::IDENTITY,
        Visibility::Inherited,
        InheritedVisibility::VISIBLE,
        ViewVisibility::default(),
        NoFrustumCulling,
        NotShadowCaster,
        Pickable::IGNORE,
    )
}

fn line_material(color: Color) -> FitOverlayLineMaterial {
    let emissive: LinearRgba = color.into();
    ExtendedMaterial {
        base:      StandardMaterial {
            base_color: color,
            emissive,
            alpha_mode: AlphaMode::Blend,
            cull_mode: None,
            unlit: true,
            ..default()
        },
        extension: FitOverlayLineDepth::default(),
    }
}

fn line_mesh(layout: &FitOverlayLayout, points: &[Vec2], closed: bool, width: f32) -> Option<Mesh> {
    if points.len() < 2 || width <= 0.0 {
        return None;
    }

    let segment_count = if closed {
        points.len()
    } else {
        points.len() - 1
    };
    let mut positions = Vec::with_capacity(segment_count * 4);
    let mut normals = Vec::with_capacity(segment_count * 4);
    let mut uvs = Vec::with_capacity(segment_count * 4);
    let mut indices = Vec::with_capacity(segment_count * 6);

    for index in 0..segment_count {
        let start = points[index];
        let end = points[(index + 1) % points.len()];
        append_segment(
            layout,
            start,
            end,
            width,
            &mut positions,
            &mut normals,
            &mut uvs,
            &mut indices,
        );
    }

    if positions.is_empty() {
        return None;
    }

    Some(
        Mesh::new(
            PrimitiveTopology::TriangleList,
            RenderAssetUsages::MAIN_WORLD | RenderAssetUsages::RENDER_WORLD,
        )
        .with_inserted_attribute(Mesh::ATTRIBUTE_POSITION, positions)
        .with_inserted_attribute(Mesh::ATTRIBUTE_NORMAL, normals)
        .with_inserted_attribute(Mesh::ATTRIBUTE_UV_0, uvs)
        .with_inserted_indices(Indices::U32(indices)),
    )
}

fn append_segment(
    layout: &FitOverlayLayout,
    start: Vec2,
    end: Vec2,
    width: f32,
    positions: &mut Vec<[f32; 3]>,
    normals: &mut Vec<[f32; 3]>,
    uvs: &mut Vec<[f32; 2]>,
    indices: &mut Vec<u32>,
) {
    let start_pixel = normalized_to_viewport(layout, start);
    let end_pixel = normalized_to_viewport(layout, end);
    let delta = end_pixel - start_pixel;
    if delta.length_squared() <= f32::EPSILON {
        return;
    }

    let normal = Vec2::new(-delta.y, delta.x).normalize() * (width * 0.5);
    let corners = [
        start_pixel + normal,
        start_pixel - normal,
        end_pixel - normal,
        end_pixel + normal,
    ];
    let Ok(base) = u32::try_from(positions.len()) else {
        return;
    };
    let Some(index_3) = base.checked_add(3) else {
        return;
    };
    for corner in corners {
        let world = viewport_to_world(layout, corner);
        positions.push(world.to_array());
        normals.push((-layout.camera_basis.forward).to_array());
    }
    uvs.extend([[0.0, 0.0], [0.0, 1.0], [1.0, 1.0], [1.0, 0.0]]);
    indices.extend([base, base + 1, base + 2, base, base + 2, index_3]);
}

fn normalized_to_viewport(layout: &FitOverlayLayout, point: Vec2) -> Vec2 {
    screen_space::norm_to_viewport(
        point.x,
        point.y,
        layout.bounds.half_extent_x,
        layout.bounds.half_extent_y,
        layout.viewport_size,
    )
    .into()
}

fn viewport_to_world(layout: &FitOverlayLayout, pixel: Vec2) -> Vec3 {
    let normalized = viewport_to_normalized(layout, pixel);
    screen_space::normalized_to_world(
        normalized.x,
        normalized.y,
        &layout.camera_basis,
        layout.average_depth,
        layout.projection_mode,
    )
}

fn viewport_to_normalized(layout: &FitOverlayLayout, pixel: Vec2) -> Vec2 {
    Vec2::new(
        (pixel.x / layout.viewport_size.x).mul_add(2.0, -1.0) * layout.bounds.half_extent_x,
        (pixel.y / layout.viewport_size.y).mul_add(-2.0, 1.0) * layout.bounds.half_extent_y,
    )
}

#[cfg(test)]
mod tests {
    use bevy::camera::NormalizedRenderTarget;
    use bevy_kana::Position;

    use super::*;
    use crate::fit::overlay::context::FitOverlayCameraContext;
    use crate::fit::overlay::frame::FitOverlayLayout;
    use crate::fit::projection::CameraBasis;
    use crate::fit::projection::ProjectionMode;
    use crate::fit::projection::ScreenSpaceBounds;

    #[derive(Resource)]
    struct TestLineCamera(Entity);

    #[derive(Resource)]
    struct TestLineLayer(u8);

    #[test]
    fn retained_line_visual_copies_source_layers_and_ignores_picking() {
        let mut app = test_app(RenderLayers::layer(7));
        let camera = app.world().resource::<TestLineCamera>().0;

        app.update();

        let mut query = app.world_mut().query::<(
            &FitOverlayVisual,
            &RenderLayers,
            &Visibility,
            &InheritedVisibility,
            &Pickable,
            &NoFrustumCulling,
            &NotShadowCaster,
        )>();
        let rows: Vec<_> = query.iter(app.world()).collect();
        assert_eq!(rows.len(), 1);
        let (visual, layers, visibility, inherited_visibility, pickable, _, _) = rows[0];
        assert_eq!(visual.camera, camera);
        assert_eq!(visual.kind, FitOverlayVisualKind::Rectangle);
        assert_eq!(layers, &RenderLayers::layer(7));
        assert_eq!(visibility, &Visibility::Inherited);
        assert_eq!(inherited_visibility, &InheritedVisibility::VISIBLE);
        assert_eq!(pickable, &Pickable::IGNORE);
    }

    #[test]
    fn retained_line_visual_repairs_source_layers_without_respawning() {
        let mut app = test_app(RenderLayers::layer(2));

        app.update();
        let first = single_line_entity(&mut app);

        app.world_mut().resource_mut::<TestLineLayer>().0 = 9;
        app.update();

        let second = single_line_entity(&mut app);
        assert_eq!(first, second);
        assert_eq!(
            app.world().get::<RenderLayers>(second),
            Some(&RenderLayers::layer(9))
        );
    }

    fn test_app(initial_layers: RenderLayers) -> App {
        let mut app = App::new();
        app.init_resource::<Assets<Mesh>>();
        app.init_resource::<Assets<FitOverlayLineMaterial>>();
        app.init_resource::<FitOverlayLineMaterials>();
        let camera = app.world_mut().spawn_empty().id();
        app.insert_resource(TestLineCamera(camera));
        app.insert_resource(TestLineLayer(layer_index(&initial_layers)));
        app.add_systems(Update, upsert_test_line);
        app
    }

    fn upsert_test_line(
        mut commands: Commands,
        mut meshes: ResMut<Assets<Mesh>>,
        mut materials: ResMut<Assets<FitOverlayLineMaterial>>,
        mut material_cache: ResMut<FitOverlayLineMaterials>,
        camera: Res<TestLineCamera>,
        layer: Res<TestLineLayer>,
        line_query: Query<FitOverlayLineQueryItem, With<FitOverlayLineVisual>>,
    ) {
        let layers = RenderLayers::layer(layer.0.into());
        let layout = test_layout(camera.0, layers);
        let line_index = retained_line_entities(&line_query);
        let mut context = FitOverlayLineContext {
            commands:       &mut commands,
            meshes:         &mut meshes,
            materials:      &mut materials,
            material_cache: &mut material_cache,
            line_index:     &line_index,
            layout:         &layout,
        };
        context.upsert_polyline(
            FitOverlayVisual {
                camera: camera.0,
                kind:   FitOverlayVisualKind::Rectangle,
            },
            &[Vec2::new(-0.5, 0.0), Vec2::new(0.5, 0.0)],
            false,
            Color::WHITE,
            2.0,
        );
    }

    fn single_line_entity(app: &mut App) -> Entity {
        let mut query = app
            .world_mut()
            .query_filtered::<Entity, With<FitOverlayLineVisual>>();
        let rows: Vec<_> = query.iter(app.world()).collect();
        assert_eq!(rows.len(), 1);
        rows[0]
    }

    fn test_layout(camera: Entity, layers: RenderLayers) -> FitOverlayLayout {
        FitOverlayLayout {
            context:         FitOverlayCameraContext {
                camera,
                normalized_target: NormalizedRenderTarget::None {
                    width:  100,
                    height: 100,
                },
                logical_viewport: Rect::new(0.0, 0.0, 100.0, 100.0),
                layers,
                order: 0,
                is_active: true,
            },
            vertices:        Vec::new(),
            bounds:          ScreenSpaceBounds {
                left_margin:      0.25,
                right_margin:     0.25,
                top_margin:       0.25,
                bottom_margin:    0.25,
                min_normalized_x: -0.5,
                max_normalized_x: 0.5,
                min_normalized_y: -0.5,
                max_normalized_y: 0.5,
                half_extent_x:    1.0,
                half_extent_y:    1.0,
            },
            camera_basis:    CameraBasis {
                position: Position(Vec3::ZERO),
                right:    Vec3::X,
                up:       Vec3::Y,
                forward:  Vec3::Z,
            },
            average_depth:   1.0,
            projection_mode: ProjectionMode::Orthographic,
            viewport_size:   Vec2::new(100.0, 100.0),
        }
    }

    fn layer_index(layers: &RenderLayers) -> u8 {
        if layers.intersects(&RenderLayers::layer(7)) {
            7
        } else {
            2
        }
    }
}
