[package]
default-run = "hana"
edition     = "2021"
name        = "hana"
version     = "0.1.0"

[dependencies]
error-stack.workspace = true
hana_controller.workspace = true
hana_window.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = [
  "env-filter",
  "registry",
] }
