[package]
edition = "2024"
name    = "hana_window"
version = "0.1.0"

[target.'cfg(target_os = "macos")'.dependencies]
error-stack.workspace = true
libc = "0.2.170"

[dependencies]
thiserror.workspace = true
tracing.workspace = true
