//! Runtime-generated JSON Schema for the keymap document.

use serde_json_lenient::Error;
use serde_json_lenient::Map;
use serde_json_lenient::Value;

use crate::Capability;
use crate::CommandRegistry;
use crate::Keystroke;
use crate::condition::ConditionRegistry;

/// Serializes the schema generated from the application's current keymap registries.
pub(crate) fn schema_bytes(
    command_registry: &CommandRegistry,
    condition_registry: &ConditionRegistry,
) -> Result<Vec<u8>, Error> {
    serde_json_lenient::to_vec_pretty(&schema_document(command_registry, condition_registry))
}

/// Prepends keymap-reference comments to the embedded default JSONC source.
pub(crate) fn reference_default_bytes(
    defaults: &str,
    condition_registry: &ConditionRegistry,
    protected_keystrokes: &[Keystroke],
) -> Vec<u8> {
    let mut header = String::from("// Keymap reference\n");
    if protected_keystrokes.is_empty() {
        header.push_str("// Protected recovery keystrokes: none.\n");
    } else {
        for protected_keystroke in protected_keystrokes {
            header.push_str("// Protected recovery keystroke: ");
            push_comment_text(&mut header, &protected_keystroke.to_string());
            header.push_str(".\n");
        }
    }
    for condition in condition_registry.iter() {
        header.push_str("// Context `");
        header.push_str(condition.name.as_str());
        header.push_str("`: ");
        push_comment_text(&mut header, condition.description);
        header.push('\n');
    }
    header.push('\n');

    let mut bytes = header.into_bytes();
    bytes.extend_from_slice(defaults.as_bytes());
    bytes
}

fn push_comment_text(header: &mut String, text: &str) {
    let mut lines = text.split('\n');
    if let Some(first_line) = lines.next() {
        header.push_str(first_line);
    }
    for line in lines {
        header.push_str("\n// ");
        header.push_str(line);
    }
}

fn schema_document(
    command_registry: &CommandRegistry,
    condition_registry: &ConditionRegistry,
) -> Value {
    let command_alternatives = command_alternatives(command_registry);
    let condition_alternatives = condition_alternatives(condition_registry);
    let binding_value_schema = binding_value_schema(command_alternatives);
    let context_schema = context_schema(condition_alternatives);
    let block_schema = block_schema(binding_value_schema, context_schema);

    serde_json_lenient::json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Hana keymap",
        "description": "Generated by hana_rubric at application startup. This file is overwritten on the next launch.",
        "type": "object",
        "properties": {
            "$schema": {
                "type": "string",
                "description": "Relative path to the generated Hana keymap schema."
            },
            "bindings": {
                "type": "array",
                "description": "Ordered keymap blocks. Later blocks override earlier bindings at the same identity.",
                "items": block_schema
            }
        },
        "required": ["bindings"],
        "additionalProperties": false
    })
}

fn command_alternatives(command_registry: &CommandRegistry) -> Vec<Value> {
    command_registry
        .iter()
        .filter(|command| command.capability.is_user_bindable())
        .map(|command| {
            let description = command_description(command.description, command.capability);

            serde_json_lenient::json!({
                "type": "string",
                "const": command.id.as_str(),
                "description": description
            })
        })
        .collect()
}

fn command_description(description: &str, capability: Capability) -> String {
    if capability == Capability::Held {
        format!(
            "{description} A held command can be bound to one keystroke only, not a multi-key sequence."
        )
    } else {
        description.to_owned()
    }
}

fn condition_alternatives(condition_registry: &ConditionRegistry) -> Vec<Value> {
    condition_registry
        .iter()
        .map(|condition| {
            serde_json_lenient::json!({
                "type": "string",
                "const": condition.name.as_str(),
                "description": condition.description
            })
        })
        .collect()
}

fn binding_value_schema(command_alternatives: Vec<Value>) -> Value {
    let mut alternatives = command_alternatives;
    alternatives.push(serde_json_lenient::json!({
        "type": "null",
        "description": "Removes the binding at this key and context identity. The key is inert here rather than inherited from an earlier block."
    }));

    serde_json_lenient::json!({ "anyOf": alternatives })
}

fn context_schema(condition_alternatives: Vec<Value>) -> Value {
    if condition_alternatives.is_empty() {
        return serde_json_lenient::json!({
            "description": "No keymap contexts are registered by this application.",
            "not": {}
        });
    }

    serde_json_lenient::json!({ "anyOf": condition_alternatives })
}

fn block_schema(binding_value_schema: Value, context_schema: Value) -> Value {
    let mut properties = Map::new();
    properties.insert(
        "bindings".to_owned(),
        serde_json_lenient::json!({
            "type": "object",
            "description": "Maps a keystroke sequence to a command or null tombstone.",
            "propertyNames": {
                "type": "string",
                "description": "A Hana keystroke sequence. Modifiers before an ordinary key form a chord. A bare shift, ctrl, alt, or secondary modifier family is valid only as the sole keystroke bound to a held command."
            },
            "additionalProperties": binding_value_schema
        }),
    );
    properties.insert("context".to_owned(), context_schema);

    serde_json_lenient::json!({
        "type": "object",
        "properties": properties,
        "required": ["bindings"],
        "additionalProperties": false
    })
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    reason = "tests should stop when schema construction unexpectedly fails"
)]
mod tests {
    use bevy::prelude::Event;
    use bevy::prelude::Reflect;
    use bevy::prelude::ReflectEvent;
    use bevy::reflect::TypeRegistry;
    use bevy_enhanced_input::prelude::CustomInputs;
    use jsonschema::Validator;
    use serde_json_lenient::Value;
    use strum::AsRefStr;
    use strum::EnumIter;
    use strum::EnumMessage;

    use crate::Capability;
    use crate::CommandRegistry;
    use crate::HoldPhase;
    use crate::KeymapCommand;
    use crate::Keystroke;
    use crate::ReflectKeymapCommand;
    use crate::condition::ConditionRegistry;
    use crate::keymap;
    use crate::keymap::KeymapDocument;
    use crate::keymap::document::RECOGNIZED_ROOT_MEMBERS;
    use crate::keymap::merged::RECOGNIZED_BLOCK_MEMBERS;

    #[derive(AsRefStr, Clone, Copy, Debug, EnumIter, EnumMessage, Eq, PartialEq)]
    #[strum(serialize_all = "snake_case")]
    enum TestContext {
        #[strum(
            message = "While the dimension lock is active\nThe locked dimension determines the available commands."
        )]
        DimensionLock,
        #[strum(message = "While the selected tool is active")]
        SelectedTool,
    }

    #[derive(Default, Event, Reflect)]
    #[reflect(Event, KeymapCommand)]
    struct CameraHome;

    impl KeymapCommand for CameraHome {
        const ID: &'static str = "camera::home";
        const TITLE: &'static str = "Camera Home";
        const DESCRIPTION: &'static str = "Returns the camera to its home position.";
        const CAPABILITY: Capability = Capability::OneShot;

        fn build() -> Self { Self }

        fn hold_phase(&self) -> Option<HoldPhase> { None }
    }

    #[derive(Event, Reflect)]
    #[reflect(Event, KeymapCommand)]
    struct CameraMove;

    impl KeymapCommand for CameraMove {
        const ID: &'static str = "camera::move";
        const TITLE: &'static str = "Camera Move";
        const DESCRIPTION: &'static str = "Moves the camera while held.";
        const CAPABILITY: Capability = Capability::Held;

        fn build() -> Self { Self }

        fn hold_phase(&self) -> Option<HoldPhase> { Some(HoldPhase::Begin) }
    }

    #[derive(Default, Event, Reflect)]
    #[reflect(Event, KeymapCommand)]
    struct RecoveryOpen;

    impl KeymapCommand for RecoveryOpen {
        const ID: &'static str = "recovery::open";
        const TITLE: &'static str = "Recovery Open";
        const DESCRIPTION: &'static str = "Opens the recovery command.";
        const CAPABILITY: Capability = Capability::Unremappable;

        fn build() -> Self { Self }

        fn hold_phase(&self) -> Option<HoldPhase> { None }
    }

    fn registries() -> Result<(CommandRegistry, ConditionRegistry), String> {
        let mut type_registry = TypeRegistry::default();
        type_registry.register::<CameraHome>();
        type_registry.register::<CameraMove>();
        type_registry.register::<RecoveryOpen>();
        let mut custom_inputs = CustomInputs::default();
        let command_registry = CommandRegistry::build(&type_registry, &mut custom_inputs)
            .map_err(|diagnostics| format!("command registry errors: {diagnostics:?}"))?;
        let mut condition_registry = ConditionRegistry::default();
        condition_registry
            .register::<TestContext>()
            .map_err(|diagnostics| format!("condition registry errors: {diagnostics:?}"))?;

        Ok((command_registry, condition_registry))
    }

    fn generated_schema(
        command_registry: &CommandRegistry,
        condition_registry: &ConditionRegistry,
    ) -> Result<Value, String> {
        let bytes = keymap::schema_bytes(command_registry, condition_registry)
            .map_err(|error| format!("schema serialization error: {error}"))?;

        serde_json_lenient::from_slice(&bytes)
            .map_err(|error| format!("schema JSON parse error: {error}"))
    }

    fn value_field<'value>(value: &'value Value, field: &str) -> Result<&'value Value, String> {
        value
            .get(field)
            .ok_or_else(|| format!("schema is missing `{field}`"))
    }

    fn value_array<'value>(value: &'value Value, field: &str) -> Result<&'value [Value], String> {
        value_field(value, field)?
            .as_array()
            .map(Vec::as_slice)
            .ok_or_else(|| format!("schema `{field}` is not an array"))
    }

    fn block_schema(schema: &Value) -> Result<&Value, String> {
        value_field(
            value_field(value_field(schema, "properties")?, "bindings")?,
            "items",
        )
    }

    fn binding_value_schema(schema: &Value) -> Result<&Value, String> {
        value_field(
            value_field(block_schema(schema)?, "properties")?
                .get("bindings")
                .ok_or_else(|| String::from("block schema is missing `bindings`"))?,
            "additionalProperties",
        )
    }

    fn alternatives_with_type<'schema>(
        schema: &'schema Value,
        value_type: &str,
    ) -> Result<Vec<&'schema Value>, String> {
        Ok(value_array(schema, "anyOf")?
            .iter()
            .filter(|alternative| {
                alternative
                    .get("type")
                    .and_then(serde_json_lenient::Value::as_str)
                    == Some(value_type)
            })
            .collect())
    }

    fn alternative_for_const<'value>(
        alternatives: &'value [Value],
        constant: &str,
    ) -> Result<&'value Value, String> {
        alternatives
            .iter()
            .find(|alternative| {
                alternative
                    .get("const")
                    .and_then(serde_json_lenient::Value::as_str)
                    == Some(constant)
            })
            .ok_or_else(|| format!("schema has no completion for `{constant}`"))
    }

    fn draft_seven_validator(schema: &Value) -> Result<Validator, String> {
        let schema = serde_json::to_value(schema)
            .map_err(|error| format!("schema JSON conversion error: {error}"))?;

        jsonschema::draft7::new(&schema)
            .map_err(|error| format!("Draft-07 schema compilation error: {error}"))
    }

    fn jsonc_document(source: &str) -> Result<serde_json::Value, String> {
        serde_json_lenient::from_str::<serde_json::Value>(source)
            .map_err(|error| format!("keymap JSONC parse error: {error}"))
    }

    #[test]
    fn schema_is_valid_json_with_draft_seven_document_members() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;

        assert_eq!(
            value_field(&schema, "$schema")?.as_str(),
            Some("http://json-schema.org/draft-07/schema#")
        );
        assert!(value_field(&schema, "description")?.is_string());
        assert_eq!(value_field(&schema, "type")?.as_str(), Some("object"));
        assert!(value_field(&schema, "properties")?.is_object());
        assert!(value_array(&schema, "required")?.contains(&serde_json_lenient::json!("bindings")));

        Ok(())
    }

    #[test]
    fn every_user_bindable_command_and_condition_has_a_described_completion() -> Result<(), String>
    {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let command_alternatives = value_array(binding_value_schema(&schema)?, "anyOf")?;
        let condition_schema = value_field(
            value_field(block_schema(&schema)?, "properties")?,
            "context",
        )?;
        let condition_alternatives = value_array(condition_schema, "anyOf")?;

        for command in command_registry
            .iter()
            .filter(|command| command.capability.is_user_bindable())
        {
            let alternative = alternative_for_const(command_alternatives, command.id.as_str())?;
            let description = value_field(alternative, "description").and_then(|description| {
                description
                    .as_str()
                    .ok_or_else(|| String::from("command completion description is not text"))
            })?;

            assert!(!description.is_empty());
            assert!(description.starts_with(command.description));
            if command.capability == Capability::Held {
                assert!(description.contains("one keystroke only"));
            }
        }

        for condition in condition_registry.iter() {
            let alternative =
                alternative_for_const(condition_alternatives, condition.name.as_str())?;
            assert_eq!(
                value_field(alternative, "description")?.as_str(),
                Some(condition.description)
            );
        }

        assert!(
            alternative_for_const(command_alternatives, "recovery::open").is_err(),
            "unremappable commands must not appear in completion"
        );

        Ok(())
    }

    #[test]
    fn null_is_a_described_binding_tombstone() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let validator = draft_seven_validator(&schema)?;
        let binding_value_schema = binding_value_schema(&schema)?;
        let null_alternative =
            alternatives_with_type(binding_value_schema, "null").and_then(|alternatives| {
                alternatives
                    .into_iter()
                    .next()
                    .ok_or_else(|| String::from("schema has no null binding alternative"))
            })?;
        let document = jsonc_document(
            r#"{
                "bindings": [{
                    "bindings": { "ctrl-k": null }
                }]
            }"#,
        )?;

        assert!(
            value_field(null_alternative, "description")?
                .as_str()
                .is_some_and(|description| description.contains("inert"))
        );
        assert!(
            validator.is_valid(&document),
            "null binding tombstone should be accepted"
        );

        Ok(())
    }

    #[test]
    fn generated_schema_compiles_as_draft_seven() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;

        draft_seven_validator(&schema)?;

        Ok(())
    }

    #[test]
    fn misspelled_root_member_fails_draft_seven_validation() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let validator = draft_seven_validator(&schema)?;
        let document = jsonc_document(
            r#"{
                // A misspelling must not become an ignored keymap setting.
                "bindings": [],
                "bindngs": []
            }"#,
        )?;

        assert!(
            !validator.is_valid(&document),
            "misspelled root member should be rejected"
        );

        Ok(())
    }

    #[test]
    fn misspelled_block_member_fails_draft_seven_validation() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let validator = draft_seven_validator(&schema)?;
        let document = jsonc_document(
            r#"{
                "bindings": [{
                    "bindings": { "ctrl-k": "camera::home" },
                    // A misspelling must not become an ignored context.
                    "contxt": "dimension_lock"
                }]
            }"#,
        )?;

        assert!(
            !validator.is_valid(&document),
            "misspelled block member should be rejected"
        );

        Ok(())
    }

    #[test]
    fn correct_document_passes_draft_seven_validation() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let validator = draft_seven_validator(&schema)?;
        let document = jsonc_document(
            r#"{
                // The editor reads this path to find the generated schema.
                "$schema": "keymap.schema.json",
                "bindings": [{
                    "context": "dimension_lock",
                    "bindings": { "ctrl-k": "camera::home" }
                }]
            }"#,
        )?;

        assert!(
            validator.is_valid(&document),
            "correct keymap document should be accepted"
        );

        Ok(())
    }

    #[test]
    fn keystroke_schema_describes_bare_modifier_family_triggers() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let property_names = value_field(
            value_field(
                value_field(block_schema(&schema)?, "properties")?
                    .get("bindings")
                    .ok_or_else(|| String::from("block schema is missing `bindings`"))?,
                "propertyNames",
            )?,
            "description",
        )?
        .as_str()
        .ok_or_else(|| String::from("keystroke schema description is not text"))?;

        assert!(property_names.contains("bare shift, ctrl, alt, or secondary"));
        assert!(property_names.contains("sole keystroke bound to a held command"));
        assert!(property_names.contains("ordinary key"));
        Ok(())
    }

    #[test]
    fn block_schema_members_match_the_loader_authority() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let properties = value_field(block_schema(&schema)?, "properties")?
            .as_object()
            .ok_or_else(|| String::from("block properties are not an object"))?;
        let mut schema_members = properties.keys().map(String::as_str).collect::<Vec<_>>();
        let mut recognized_members = RECOGNIZED_BLOCK_MEMBERS.to_vec();

        schema_members.sort_unstable();
        recognized_members.sort_unstable();

        assert_eq!(schema_members, recognized_members);
        assert!(
            properties
                .values()
                .all(serde_json_lenient::Value::is_object)
        );

        Ok(())
    }

    #[test]
    fn root_schema_members_match_the_loader_authority() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let mut schema_members = value_field(&schema, "properties")?
            .as_object()
            .ok_or_else(|| String::from("root schema properties are not an object"))?
            .keys()
            .map(String::as_str)
            .collect::<Vec<_>>();
        let mut recognized_members = RECOGNIZED_ROOT_MEMBERS.to_vec();

        schema_members.sort_unstable();
        recognized_members.sort_unstable();

        assert_eq!(schema_members, recognized_members);
        Ok(())
    }

    #[test]
    fn reference_header_precedes_byte_identical_embedded_defaults() -> Result<(), String> {
        let (_, condition_registry) = registries()?;
        let defaults = "{\n  \"bindings\": []\n}\n";
        let protected_keystroke = "ctrl-g"
            .parse::<Keystroke>()
            .map_err(|error| format!("invalid protected test keystroke: {error}"))?;
        let bytes =
            keymap::reference_default_bytes(defaults, &condition_registry, &[protected_keystroke]);
        let published_defaults = std::str::from_utf8(&bytes)
            .map_err(|error| format!("reference defaults are not UTF-8: {error}"))?;
        let defaults_offset = published_defaults
            .find(defaults)
            .ok_or_else(|| String::from("reference defaults omit the embedded source"))?;
        let header = &published_defaults[..defaults_offset];

        assert!(header.contains("ctrl-g"));
        for condition in condition_registry.iter() {
            let commented_description = condition.description.replace('\n', "\n// ");

            assert!(header.contains(condition.name.as_str()));
            assert!(header.contains(&commented_description));
        }
        assert!(header.contains("// Context `selected_tool`: While the selected tool is active\n"));
        assert_eq!(&published_defaults[defaults_offset..], defaults);
        assert!(KeymapDocument::parse("published-defaults.jsonc", published_defaults).is_ok());
        Ok(())
    }
}
