//! Runtime-generated JSON Schema for the keymap document.

#![cfg_attr(
    not(test),
    expect(
        dead_code,
        reason = "the plugin's finish step is the only non-test caller of this module"
    )
)]

use serde_json_lenient::Map;
use serde_json_lenient::Value;

use crate::Capability;
use crate::CommandRegistry;
use crate::condition::ConditionRegistry;

/// Serializes the schema generated from the application's current keymap registries.
pub(crate) fn schema_bytes(
    command_registry: &CommandRegistry,
    condition_registry: &ConditionRegistry,
) -> Result<Vec<u8>, serde_json_lenient::Error> {
    serde_json_lenient::to_vec_pretty(&schema_document(command_registry, condition_registry))
}

fn schema_document(
    command_registry: &CommandRegistry,
    condition_registry: &ConditionRegistry,
) -> Value {
    let command_alternatives = command_alternatives(command_registry);
    let condition_alternatives = condition_alternatives(condition_registry);
    let binding_value_schema = binding_value_schema(command_alternatives);
    let context_schema = context_schema(condition_alternatives);
    let block_schema = block_schema(binding_value_schema, context_schema);

    serde_json_lenient::json!({
        "$schema": "http://json-schema.org/draft-07/schema#",
        "title": "Hana keymap",
        "description": "Generated by hana_rubric at application startup. This file is overwritten on the next launch.",
        "type": "object",
        "properties": {
            "$schema": {
                "type": "string",
                "description": "Relative path to the generated Hana keymap schema."
            },
            "bindings": {
                "type": "array",
                "description": "Ordered keymap blocks. Later blocks override earlier bindings at the same identity.",
                "items": block_schema
            }
        },
        "required": ["bindings"],
        "additionalProperties": false
    })
}

fn command_alternatives(command_registry: &CommandRegistry) -> Vec<Value> {
    command_registry
        .iter()
        .filter(|command| command.capability.is_user_bindable())
        .map(|command| {
            let description = command_description(command.description, command.capability);

            serde_json_lenient::json!({
                "type": "string",
                "const": command.id.as_str(),
                "description": description
            })
        })
        .collect()
}

fn command_description(description: &str, capability: Capability) -> String {
    if capability == Capability::Held {
        format!(
            "{description} A held command can be bound to one keystroke only, not a multi-key sequence."
        )
    } else {
        description.to_owned()
    }
}

fn condition_alternatives(condition_registry: &ConditionRegistry) -> Vec<Value> {
    condition_registry
        .iter()
        .map(|condition| {
            serde_json_lenient::json!({
                "type": "string",
                "const": condition.name.as_str(),
                "description": condition.description
            })
        })
        .collect()
}

fn binding_value_schema(command_alternatives: Vec<Value>) -> Value {
    let mut alternatives = command_alternatives;
    alternatives.push(serde_json_lenient::json!({
        "type": "null",
        "description": "Removes the binding at this key and context identity. The key is inert here rather than inherited from an earlier block."
    }));

    serde_json_lenient::json!({ "anyOf": alternatives })
}

fn context_schema(condition_alternatives: Vec<Value>) -> Value {
    if condition_alternatives.is_empty() {
        return serde_json_lenient::json!({
            "description": "No keymap contexts are registered by this application.",
            "not": {}
        });
    }

    serde_json_lenient::json!({ "anyOf": condition_alternatives })
}

fn block_schema(binding_value_schema: Value, context_schema: Value) -> Value {
    let mut properties = Map::new();
    properties.insert(
        "bindings".to_owned(),
        serde_json_lenient::json!({
            "type": "object",
            "description": "Maps a keystroke sequence to a command or null tombstone.",
            "propertyNames": {
                "type": "string",
                "description": "A Hana keystroke sequence."
            },
            "additionalProperties": binding_value_schema
        }),
    );
    properties.insert("context".to_owned(), context_schema);

    serde_json_lenient::json!({
        "type": "object",
        "properties": properties,
        "required": ["bindings"],
        "additionalProperties": false
    })
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    reason = "tests should stop when schema construction unexpectedly fails"
)]
mod tests {
    use bevy::prelude::Event;
    use bevy::prelude::Reflect;
    use bevy::prelude::ReflectEvent;
    use bevy::reflect::TypeRegistry;
    use bevy_enhanced_input::prelude::CustomInputs;
    use strum::AsRefStr;
    use strum::EnumIter;
    use strum::EnumMessage;

    use super::super::merged::RECOGNIZED_BLOCK_MEMBERS;
    use crate::Capability;
    use crate::CommandRegistry;
    use crate::HoldPhase;
    use crate::KeymapCommand;
    use crate::ReflectKeymapCommand;
    use crate::condition::ConditionRegistry;
    use crate::keymap::schema_bytes;

    #[derive(AsRefStr, Clone, Copy, Debug, EnumIter, EnumMessage, Eq, PartialEq)]
    #[strum(serialize_all = "snake_case")]
    enum TestContext {
        #[strum(message = "While the dimension lock is active")]
        DimensionLock,
        #[strum(message = "While the selected tool is active")]
        SelectedTool,
    }

    #[derive(Default, Event, Reflect)]
    #[reflect(Event, KeymapCommand)]
    struct CameraHome;

    impl KeymapCommand for CameraHome {
        const ID: &'static str = "camera::home";
        const TITLE: &'static str = "Camera Home";
        const DESCRIPTION: &'static str = "Returns the camera to its home position.";
        const CAPABILITY: Capability = Capability::OneShot;

        fn hold_phase(&self) -> Option<HoldPhase> { None }
    }

    #[derive(Event, Reflect)]
    #[reflect(Event, KeymapCommand)]
    struct CameraMove;

    impl KeymapCommand for CameraMove {
        const ID: &'static str = "camera::move";
        const TITLE: &'static str = "Camera Move";
        const DESCRIPTION: &'static str = "Moves the camera while held.";
        const CAPABILITY: Capability = Capability::Held;

        fn hold_phase(&self) -> Option<HoldPhase> { Some(HoldPhase::Begin) }
    }

    #[derive(Default, Event, Reflect)]
    #[reflect(Event, KeymapCommand)]
    struct RecoveryOpen;

    impl KeymapCommand for RecoveryOpen {
        const ID: &'static str = "recovery::open";
        const TITLE: &'static str = "Recovery Open";
        const DESCRIPTION: &'static str = "Opens the recovery command.";
        const CAPABILITY: Capability = Capability::Unremappable;

        fn hold_phase(&self) -> Option<HoldPhase> { None }
    }

    fn registries() -> Result<(CommandRegistry, ConditionRegistry), String> {
        let mut type_registry = TypeRegistry::default();
        type_registry.register::<CameraHome>();
        type_registry.register::<CameraMove>();
        type_registry.register::<RecoveryOpen>();
        let mut custom_inputs = CustomInputs::default();
        let command_registry = CommandRegistry::build(&type_registry, &mut custom_inputs)
            .map_err(|diagnostics| format!("command registry errors: {diagnostics:?}"))?;
        let mut condition_registry = ConditionRegistry::default();
        condition_registry
            .register::<TestContext>()
            .map_err(|diagnostics| format!("condition registry errors: {diagnostics:?}"))?;

        Ok((command_registry, condition_registry))
    }

    fn generated_schema(
        command_registry: &CommandRegistry,
        condition_registry: &ConditionRegistry,
    ) -> Result<serde_json_lenient::Value, String> {
        let bytes = schema_bytes(command_registry, condition_registry)
            .map_err(|error| format!("schema serialization error: {error}"))?;

        serde_json_lenient::from_slice(&bytes)
            .map_err(|error| format!("schema JSON parse error: {error}"))
    }

    fn value_field<'value>(
        value: &'value serde_json_lenient::Value,
        field: &str,
    ) -> Result<&'value serde_json_lenient::Value, String> {
        value
            .get(field)
            .ok_or_else(|| format!("schema is missing `{field}`"))
    }

    fn value_array<'value>(
        value: &'value serde_json_lenient::Value,
        field: &str,
    ) -> Result<&'value [serde_json_lenient::Value], String> {
        value_field(value, field)?
            .as_array()
            .map(Vec::as_slice)
            .ok_or_else(|| format!("schema `{field}` is not an array"))
    }

    fn block_schema(
        schema: &serde_json_lenient::Value,
    ) -> Result<&serde_json_lenient::Value, String> {
        value_field(
            value_field(value_field(schema, "properties")?, "bindings")?,
            "items",
        )
    }

    fn binding_value_schema(
        schema: &serde_json_lenient::Value,
    ) -> Result<&serde_json_lenient::Value, String> {
        value_field(
            value_field(block_schema(schema)?, "properties")?
                .get("bindings")
                .ok_or_else(|| String::from("block schema is missing `bindings`"))?,
            "additionalProperties",
        )
    }

    fn alternatives_with_type<'schema>(
        schema: &'schema serde_json_lenient::Value,
        value_type: &str,
    ) -> Result<Vec<&'schema serde_json_lenient::Value>, String> {
        Ok(value_array(schema, "anyOf")?
            .iter()
            .filter(|alternative| {
                alternative
                    .get("type")
                    .and_then(serde_json_lenient::Value::as_str)
                    == Some(value_type)
            })
            .collect())
    }

    fn alternative_for_const<'value>(
        alternatives: &'value [serde_json_lenient::Value],
        constant: &str,
    ) -> Result<&'value serde_json_lenient::Value, String> {
        alternatives
            .iter()
            .find(|alternative| {
                alternative
                    .get("const")
                    .and_then(serde_json_lenient::Value::as_str)
                    == Some(constant)
            })
            .ok_or_else(|| format!("schema has no completion for `{constant}`"))
    }

    fn validate_against_schema(
        schema: &serde_json_lenient::Value,
        value: &serde_json_lenient::Value,
    ) -> Result<(), String> {
        if let Some(constant) = schema.get("const")
            && value != constant
        {
            return Err(format!("value does not equal schema const `{constant}`"));
        }

        if let Some(alternatives) = schema.get("anyOf") {
            let alternatives = alternatives
                .as_array()
                .ok_or_else(|| String::from("schema `anyOf` is not an array"))?;
            if !alternatives
                .iter()
                .any(|alternative| validate_against_schema(alternative, value).is_ok())
            {
                return Err(String::from("value does not match any schema alternative"));
            }
        }

        if schema.get("not").is_some() {
            return Err(String::from("value is excluded by the schema"));
        }

        if let Some(value_type) = schema
            .get("type")
            .and_then(serde_json_lenient::Value::as_str)
        {
            let type_matches = match value_type {
                "array" => value.is_array(),
                "null" => value.is_null(),
                "object" => value.is_object(),
                "string" => value.is_string(),
                _ => return Err(format!("unsupported schema type `{value_type}`")),
            };
            if !type_matches {
                return Err(format!("value is not a `{value_type}`"));
            }
        }

        if let Some(items) = schema.get("items") {
            let array = value
                .as_array()
                .ok_or_else(|| String::from("schema items requires an array value"))?;
            for item in array {
                validate_against_schema(items, item)?;
            }
        }

        let Some(object) = value.as_object() else {
            return Ok(());
        };
        if let Some(required) = schema.get("required") {
            for field in required
                .as_array()
                .ok_or_else(|| String::from("schema `required` is not an array"))?
            {
                let field = field
                    .as_str()
                    .ok_or_else(|| String::from("schema `required` contains a non-string"))?;
                if !object.contains_key(field) {
                    return Err(format!("object is missing required `{field}`"));
                }
            }
        }

        let properties = schema
            .get("properties")
            .and_then(serde_json_lenient::Value::as_object);
        for (field, field_value) in object {
            if let Some(property_schema) = properties.and_then(|properties| properties.get(field)) {
                validate_against_schema(property_schema, field_value)?;
                continue;
            }

            match schema.get("additionalProperties") {
                Some(serde_json_lenient::Value::Bool(false)) => {
                    return Err(format!("object has unrecognized `{field}`"));
                },
                Some(serde_json_lenient::Value::Bool(true)) | None => {},
                Some(property_schema) => validate_against_schema(property_schema, field_value)?,
            }
        }

        Ok(())
    }

    #[test]
    fn schema_is_valid_json_with_draft_seven_document_members() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;

        assert_eq!(
            value_field(&schema, "$schema")?.as_str(),
            Some("http://json-schema.org/draft-07/schema#")
        );
        assert!(value_field(&schema, "description")?.is_string());
        assert_eq!(value_field(&schema, "type")?.as_str(), Some("object"));
        assert!(value_field(&schema, "properties")?.is_object());
        assert!(value_array(&schema, "required")?.contains(&serde_json_lenient::json!("bindings")));

        Ok(())
    }

    #[test]
    fn every_user_bindable_command_and_condition_has_a_described_completion() -> Result<(), String>
    {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let command_alternatives = value_array(binding_value_schema(&schema)?, "anyOf")?;
        let condition_schema = value_field(
            value_field(block_schema(&schema)?, "properties")?,
            "context",
        )?;
        let condition_alternatives = value_array(condition_schema, "anyOf")?;

        for command in command_registry
            .iter()
            .filter(|command| command.capability.is_user_bindable())
        {
            let alternative = alternative_for_const(command_alternatives, command.id.as_str())?;
            let description = value_field(alternative, "description").and_then(|description| {
                description
                    .as_str()
                    .ok_or_else(|| String::from("command completion description is not text"))
            })?;

            assert!(!description.is_empty());
            assert!(description.starts_with(command.description));
            if command.capability == Capability::Held {
                assert!(description.contains("one keystroke only"));
            }
        }

        for condition in condition_registry.iter() {
            let alternative =
                alternative_for_const(condition_alternatives, condition.name.as_str())?;
            assert_eq!(
                value_field(alternative, "description")?.as_str(),
                Some(condition.description)
            );
        }

        assert!(
            alternative_for_const(command_alternatives, "recovery::open").is_err(),
            "unremappable commands must not appear in completion"
        );

        Ok(())
    }

    #[test]
    fn null_is_a_described_binding_tombstone() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let binding_value_schema = binding_value_schema(&schema)?;
        let null_alternative =
            alternatives_with_type(binding_value_schema, "null").and_then(|alternatives| {
                alternatives
                    .into_iter()
                    .next()
                    .ok_or_else(|| String::from("schema has no null binding alternative"))
            })?;
        let document = serde_json_lenient::json!({
            "bindings": [{ "bindings": { "ctrl-k": null } }]
        });

        assert!(
            value_field(null_alternative, "description")?
                .as_str()
                .is_some_and(|description| description.contains("inert"))
        );
        validate_against_schema(&schema, &document)?;

        Ok(())
    }

    #[test]
    fn root_and_block_reject_additional_properties() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let misspelled_block_member = serde_json_lenient::json!({
            "bindings": [{
                "bindings": { "ctrl-k": "camera::home" },
                "contxt": "dimension_lock"
            }]
        });

        assert_eq!(
            value_field(&schema, "additionalProperties")?.as_bool(),
            Some(false)
        );
        assert_eq!(
            value_field(block_schema(&schema)?, "additionalProperties")?.as_bool(),
            Some(false)
        );
        let error = validate_against_schema(&schema, &misspelled_block_member)
            .expect_err("misspelled block member should be rejected");
        assert!(error.contains("contxt"));

        Ok(())
    }

    #[test]
    fn block_schema_members_match_the_loader_authority() -> Result<(), String> {
        let (command_registry, condition_registry) = registries()?;
        let schema = generated_schema(&command_registry, &condition_registry)?;
        let properties = value_field(block_schema(&schema)?, "properties")?
            .as_object()
            .ok_or_else(|| String::from("block properties are not an object"))?;
        let mut schema_members = properties.keys().map(String::as_str).collect::<Vec<_>>();
        let mut recognized_members = RECOGNIZED_BLOCK_MEMBERS.to_vec();

        schema_members.sort_unstable();
        recognized_members.sort_unstable();

        assert_eq!(schema_members, recognized_members);
        assert!(
            properties
                .values()
                .all(serde_json_lenient::Value::is_object)
        );

        Ok(())
    }
}
