[package]
edition = "2021"
name    = "hana_network"
version = "0.1.0"

[dependencies]
bincode               = { version = "1.3.3" }
# error-stack.workspace = true
serde                 = { version = "1.0.217", features = ["derive"] }
thiserror             = { version = "2.0.11" }
