name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build
      - name: Run Windows IPC tests with output
        if: runner.os == 'Windows'
        run: cargo test transport::ipc::windows -- --nocapture
      - name: Run all tests
        run: cargo test --verbose
