name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: |
          # On Windows, make it easier to see test debug output
          if [ "$RUNNER_OS" == "Windows" ]; then
            cargo test transport::ipc::windows -- --nocapture
          else
            cargo test --verbose
          fi
